HIVE-14245. NoClassDefFoundError when starting LLAP daemon. (Rajesh Balamohan, reviewed by Gopal V)
(cherry picked from commit 07c20035fb426416d999b6be54256953a1b7c8ab)